PublicController:
    path: /
    controller: App\Controller\PublicController::home

admin:
    path: /admin/
    controller: App\Controller\Admin\AdminController::home
    methods: GET|POST

app_login:
    path: /login/
    controller: App\Controller\SecurityController::login
    methods: GET|POST

app_logout:
    path: /logout/
    controller: App\Controller\SecurityController::logout
    methods: GET|POST

utilisateur_delete:
    path: /admin/utilisateur_delete{id}
    controller: App\Controller\Admin\AdminController::utilisateur_delete
    methods: GET|POST|DELETE